### ISSUE TITLE
Synchronize Data Retrieval

### ISSUE THREAD

**Issue by rahulbijoor** [ChicoState/chronicle#15]
Observed Behavior
When a user enters the repository name, the data is automatically fetched from GitHub without clicking the "Search" button. Additionally, the data fetched automatically does not include code reviews. Furthermore, there is a delay between when the user clicks the view details and export data buttons appear and the entire data is fetched. During this time if the user exports data incomplete data is fetched.  

Expected Behavior
Data should only be fetched from GitHub when the "Search" button is pressed. The fetched data should be complete data.

Acceptance Criteria

- [x] The application should not automatically fetch data when the repository name is entered.
- [x] Data should only be fetched when the "Search" button is pressed.
- [x] The "View Details" and "Export Data" buttons should only appear once all data has been fully fetched to prevent incomplete data export.

**Comment by kbuffardi** [comment]
Closed #16
